'use client'

import { createContext, useContext, useEffect, useState } from 'react'

// ============================================================
// Theme (light / dark) + Language (en / ar) providers
// ============================================================

type Theme = 'light' | 'dark'
type Lang  = 'en' | 'ar'

const THEME_KEY = 'schedoo-theme'
const LANG_KEY  = 'schedoo-lang'

interface AppCtx {
  theme: Theme
  toggleTheme: () => void
  lang: Lang
  setLang: (l: Lang) => void
  toggleLang: () => void
  t: (key: string) => string
  dir: 'rtl' | 'ltr'
}

const Ctx = createContext<AppCtx | null>(null)

export function AppProviders({ children }: { children: React.ReactNode }) {
  const [theme, setTheme] = useState<Theme>('light')
  const [lang, setLangState] = useState<Lang>('en')

  // hydrate from localStorage on mount
  useEffect(() => {
    const savedTheme = (localStorage.getItem(THEME_KEY) as Theme) || 'light'
    const savedLang  = (localStorage.getItem(LANG_KEY)  as Lang)  || 'en'
    setTheme(savedTheme)
    setLangState(savedLang)
  }, [])

  // apply theme
  useEffect(() => {
    document.documentElement.classList.toggle('dark', theme === 'dark')
    localStorage.setItem(THEME_KEY, theme)
  }, [theme])

  // apply language + direction
  useEffect(() => {
    const dir = lang === 'ar' ? 'rtl' : 'ltr'
    document.documentElement.setAttribute('lang', lang)
    document.documentElement.setAttribute('dir', dir)
    localStorage.setItem(LANG_KEY, lang)
  }, [lang])

  const dir: 'rtl' | 'ltr' = lang === 'ar' ? 'rtl' : 'ltr'

  const value: AppCtx = {
    theme,
    toggleTheme: () => setTheme(t => (t === 'dark' ? 'light' : 'dark')),
    lang,
    setLang: setLangState,
    toggleLang: () => setLangState(l => (l === 'ar' ? 'en' : 'ar')),
    t: (key: string) => DICT[lang][key] ?? DICT.en[key] ?? key,
    dir,
  }

  return <Ctx.Provider value={value}>{children}</Ctx.Provider>
}

export function useApp() {
  const ctx = useContext(Ctx)
  if (!ctx) throw new Error('useApp must be used within AppProviders')
  return ctx
}

// ============================================================
// Translation dictionary
// ============================================================

type Dict = Record<string, string>

const en: Dict = {
  // shell / nav
  'nav.company':      'Company',
  'nav.teams':        'Teams',
  'nav.appearance':   'Appearance',
  'nav.language':     'Language',
  'nav.signOut':      'Sign out',
  'nav.backToTeams':  '← Teams',
  'theme.light':      'Light',
  'theme.dark':       'Dark',

  // dashboard (company)
  'dash.subtitle':    'Accounts, teams and shift schedules',
  'dash.newAccount':  'New account',
  'dash.createAccount': 'Create a new account',
  'dash.accountName': 'Account name',
  'dash.coverage':    'Coverage type',
  'dash.weekStart':   'Week starts on',
  'dash.cancel':      'Cancel',
  'dash.saveAccount': '+ Create account',
  'dash.saving':      'Saving…',
  'dash.loading':     'Loading…',
  'dash.noAccounts':  'No accounts yet',
  'dash.noAccountsHint': 'Start by creating your first account (business unit) to organize your teams',
  'dash.addTeam':     'Add team',
  'dash.noTeams':     'No teams in this account yet',
  'dash.teamName':    'Team name',
  'dash.coAdmins':    'Co-admin emails',
  'dash.managers':    'Manager emails',
  'dash.optional':    '(optional)',
  'dash.saveTeam':    '+ Create team',
  'dash.teamsCount':  'teams',
  'dash.managersCount': 'managers',
  'coverage.custom':  'Custom',
  'coverage.24_7':    '24/7 coverage',

  // team management
  'team.management':  'Team Management',
  'team.subtitle':    'Configure your team and manage weekly schedules',
  'team.shifts':      'Shifts',
  'team.shifts.desc': 'Define shift types, times, and colors',
  'team.requirements': 'Requirements',
  'team.requirements.desc': 'Min & Max agents per shift per day',
  'team.agents':      'Agents',
  'team.agents.desc': 'Add agents and approve accounts',
  'team.schedule':    'Schedule',
  'team.schedule.desc': 'View matrix, validate, and export',
  'team.reports':     'Reports',
  'team.reports.desc': 'Monthly shift stats and workload',
  'team.leaves':      'Leaves & Balances',
  'team.leaves.desc': 'Employee balances and leave requests',
  'team.holidays':    'Public Holidays',
  'team.holidays.desc': 'Official holidays and compensation tracking',
  'team.settings':    'Settings',
  'team.settings.desc': 'Admins, managers, and team config',

  // days
  'day.0': 'Sunday', 'day.1': 'Monday', 'day.2': 'Tuesday', 'day.3': 'Wednesday',
  'day.4': 'Thursday', 'day.5': 'Friday', 'day.6': 'Saturday',
  'dayShort.0': 'Sun', 'dayShort.1': 'Mon', 'dayShort.2': 'Tue', 'dayShort.3': 'Wed',
  'dayShort.4': 'Thu', 'dayShort.5': 'Fri', 'dayShort.6': 'Sat',

  // common
  'common.backToTeam': '← Team',
  'common.loading':    'Loading…',
  'common.add':        'Add',
  'common.saved':      '✓ Saved!',

  // auth
  'auth.tagline':    'Sign in to manage your team schedules',
  'auth.google':     'Continue with Google',
  'auth.orEmail':    'or email',
  'auth.email':      'Email',
  'auth.password':   'Password',
  'auth.signingIn':  'Signing in…',
  'auth.signIn':     'Sign In',
  'auth.signUp':     'Sign Up',
  'auth.checkEmail': 'Check your email to confirm your account.',

  // shifts
  'shifts.title':         'Shift Configuration',
  'shifts.addType':       'Add Shift Type',
  'shifts.name':          'Name',
  'shifts.namePlaceholder':'e.g. Morning',
  'shifts.start':         'Start Time',
  'shifts.end':           'End Time',
  'shifts.color':         'Color',
  'shifts.isOff':         'This is an "OFF / Day Off" shift',
  'shifts.adding':        'Adding…',
  'shifts.add':           'Add Shift',
  'shifts.colShift':      'Shift',
  'shifts.colHours':      'Hours',
  'shifts.colType':       'Type',
  'shifts.dayOff':        'Day Off',
  'shifts.shift':         'Shift',
  'shifts.none':          'No shifts defined yet',
  'shifts.confirmDelete': 'Delete this shift?',

  // requirements
  'req.title':    'Requirements Matrix',
  'req.subtitle': 'Min and Max agents per shift per day — leave Max empty for no limit',
  'req.saveAll':  'Save All',
  'req.saving':   'Saving…',
  'req.minMax':   'Min / Max',
  'req.noShifts': 'No shifts defined yet.',
  'req.addFirst': 'Add shifts first',
  'req.minTitle': 'Minimum',
  'req.maxTitle': 'Maximum (empty = no limit)',

  // team settings
  'set.title':         'Team Settings',
  'set.teamName':      'Team Name',
  'set.coAdmins':      'Co-Admins',
  'set.coAdminsHint':  'They can sign in and manage the team with their emails',
  'set.noCoAdmins':    'No co-admins yet',
  'set.managerEmails': 'Manager Emails',
  'set.managerHint':   'They receive the final schedule by email',
  'set.noManagers':    'No managers yet',
  'set.saveChanges':   'Save Changes',

  'common.cancel': 'Cancel',

  // agents
  'agents.title':          'Agents',
  'agents.namePlaceholder':'Agent name',
  'agents.emailPlaceholder':'Company email (for sign-in)',
  'agents.adding':         'Adding…',
  'agents.add':            'Add',
  'agents.hint':           'The agent signs up with this email, then you approve their access from the table below.',
  'agents.colAgent':       'Agent',
  'agents.colEmail':       'Email',
  'agents.colStatus':      'Status',
  'agents.noEmail':        '— no email —',
  'agents.active':         '✓ Active',
  'agents.pending':        '⏳ Awaiting approval',
  'agents.notSignedUp':    'Not signed up yet',
  'agents.noAccount':      'No account',
  'agents.approve':        '✓ Approve',
  'agents.revoke':         'Revoke',
  'agents.move':           'Move',
  'agents.moveTo':         'Move to another team',
  'agents.none':           'No agents yet',
  'agents.confirmDelete':  'Delete this agent and all their schedules permanently? Use Move instead if you want to relocate them.',
  'agents.moveHeading':    'Move Agent',
  'agents.moveDescPre':    'Move',
  'agents.moveDescPost':   'to another team. Their new registration will be on the new team. Old schedules stay on the current team.',
  'agents.noOtherTeams':   'No other team to move to. Create a team first.',
  'agents.chooseTeam':     'Choose the new team',
  'agents.choose':         '— choose —',
  'agents.moving':         'Moving…',
  'agents.moveBtn':        'Move Agent',

  // leaves
  'leaves.subtitle':      'Set each employee balance and review leave requests',
  'leaves.pending':       'Pending review',
  'leaves.noPending':     'No pending requests',
  'leaves.days':          'days',
  'leaves.approve':       'Approve',
  'leaves.reject':        'Reject',
  'leaves.colEmployee':   'Employee',
  'leaves.annualBalance': 'Annual balance',
  'leaves.usedRemaining': 'Used / Remaining',
  'leaves.sickBalance':   'Sick balance',
  'leaves.save':          'Save',
  'leaves.noEmployees':   'No employees',
  'leaveType.annual':     'Annual',
  'leaveType.sick':       'Sick',
  'leaveType.unpaid':     'Unpaid',

  // holidays
  'hol.title':          'Public Holidays & Compensation',
  'hol.subtitle':       'Track who worked on public holidays and who took their comp day',
  'hol.granted':        'Comp granted',
  'hol.pendingStat':    'Pending',
  'hol.usedStat':       'Comp used',
  'hol.add':            'Add public holiday',
  'hol.date':           'Date',
  'hol.name':           'Holiday name',
  'hol.namePlaceholder':'e.g. Eid al-Adha',
  'hol.adding':         'Adding…',
  'hol.addBtn':         '+ Add',
  'hol.none':           'No public holidays added yet',
  'hol.confirmDelete':  'Delete this holiday? Related compensation records will be deleted.',
  'hol.compBadge':      'comp',
  'hol.usedBadge':      'used',
  'hol.searching':      'Searching…',
  'hol.noWorkers':      'No agents scheduled on this day',
  'hol.workedThisDay':  'Worked this day',
  'hol.grantAll':       'Grant comp to all',
  'hol.grant':          'Grant comp',
  'hol.usedOn':         'Used',
  'hol.undo':           'Undo',
  'hol.compGranted':    'Comp granted',
  'hol.markUsed':       '✓ Mark used',
  'hol.pendingSummary': 'Compensation not used yet',
  'hol.recordUse':      'Record use',

  // reports
  'rep.loading':        'Loading report…',
  'rep.title':          'Team Reports',
  'rep.subtitle':       'Per-agent shift stats over the month',
  'rep.agents':         'Agents',
  'rep.workShifts':     'Work shifts',
  'rep.offDays':        'OFF days',
  'rep.monthHolidays':  'Holidays this month',
  'rep.noAgents':       'No agents',
  'rep.colAgent':       'Agent',
  'rep.total':          'Total',
  'rep.nights':         'Nights 🌙',
  'rep.weekends':       'Fri/Sat',
  'rep.holidaysWorked': 'Holidays worked',
  'rep.comp':           'Comp',
  'rep.grandTotal':     'Total',
  'rep.used':           'used',
  'rep.hint':           '💡 Click any agent to see their full month calendar and comp details.',
  'rep.compDays':       'Compensation days',
  'rep.compUsedOn':     '✓ Compensated on',
  'rep.compNotUsed':    '⏳ Comp not used',
  'rep.compNotGranted': 'Not granted',

  // schedule
  'sched.loading':        'Loading schedule…',
  'sched.title':          'Schedule Matrix',
  'sched.ok':             '✓ OK',
  'sched.less':           '▼ LESS',
  'sched.more':           '▲ MORE',
  'sched.fridayTitle':    '⚠️ Warning — it is Friday and the schedule is not confirmed yet!',
  'sched.fridayDesc':     'It is recommended to confirm the schedule and send it to the manager before end of day.',
  'sched.confirmNow':     '🔒 Confirm now',
  'sched.confirming':     'Confirming…',
  'sched.confirmed':      '🔒 Confirmed',
  'sched.open':           '🟡 Open',
  'sched.confirm':        'Confirm schedule',
  'sched.openNext':       'Open next week',
  'sched.opening':        'Opening…',
  'sched.exporting':      'Exporting…',
  'sched.exportEmail':    'Export & Email',
  'sched.editHint':       '💡 You can assign or change any employee shift directly from the grid — click a cell and pick a shift (to fill gaps or for non-registrants).',
  'sched.noAgents':       'No agents yet.',
  'sched.addAgentsFirst': 'Add agents first',
  'sched.colAgent':       'Agent',
  'sched.notRegistered':  '— not registered —',
  'sched.assignTitle':    'Assign or change the shift',
  'sched.validation':     'Validation',
  'sched.submissions':    'Submissions',
  'sched.confirmDialog':  'Lock this schedule? Agents will no longer be able to edit their submissions.',
  'sched.confirmedToast': 'Schedule confirmed ✓',
  'sched.emailedToast':   'Sent to manager ✉️',
  'sched.exportedNoEmail':'Exported but email not sent:',
  'sched.filesCreated':   'Files created ✅',
  'sched.exportFailed':   'Export failed:',
  'sched.nextOpened':     'Next week opened for submissions ✅',
  'sched.complianceTitle':'Compliance & rest warnings',
  'sched.complianceDescPre':'Auto-check: too many consecutive days · no rest day · short rest between shifts (less than',
  'sched.complianceDescPost':'hours)',
  'sched.noIssues':       '✓ No violations in this week — all good',
  'sched.consecutiveDays':'consecutive days without rest',
  'sched.noRestDay':      'No rest day the whole week',
  'sched.shortRest':      'Short rest',
  'sched.hoursShort':     'h',
  'sched.between':        'between',
  'sched.and':            'and',

  // agent area (/me)
  'me.nav.register':    'Register schedule',
  'me.nav.month':       'My monthly schedule',
  'me.nav.leave':       'My leaves',
  'me.signOut':         'Sign out',
  'me.exit':            'Exit',
  'me.pendingTitle':    'Awaiting admin approval',
  'me.pendingHi':       'Hi',
  'me.pendingBody':     '— your account was created successfully. You still need an admin to approve your access.',
  'me.noAccessTitle':   'No access permission',
  'me.noAccessDesc':    'This email is not added to any team yet. Contact the admin.',
  'me.noOpenWeek':      'No week open for registration right now.',
  'me.shortageTitle':   'Some shifts are short — register in them and help the team 🙌',
  'me.teamSchedule':    'Team schedule',
  'me.colEmployee':     'Employee',
  'me.meSuffix':        ' (me)',
  'me.coverage':        'coverage',
  'me.short':           'short',
  'me.full':            'full',
  'me.need':            'need',
  'me.legShort':        'short',
  'me.legOk':           'ok',
  'me.legFull':         'full',
  'me.legNone':         'not registered yet',
  'me.registerMine':    '✍️ Register my schedule',
  'me.saving':          'Saving…',
  'me.saveMine':        'Save my schedule',
  'me.savedToast':      'Your schedule was saved ✅',
  'me.liveHint':        'The schedule updates live — as people register, coverage changes. Refresh for the latest.',

  // agent leaves
  'meLeave.request':    'Request leave',
  'meLeave.annual':     'Annual leave',
  'meLeave.sick':       'Sick leave',
  'meLeave.remainingOf':'remaining of',
  'meLeave.used':       'used',
  'meLeave.type':       'Leave type',
  'meLeave.from':       'From',
  'meLeave.to':         'To',
  'meLeave.reason':     'Reason (optional)',
  'meLeave.sending':    'Sending…',
  'meLeave.send':       'Send request',
  'meLeave.myRequests': 'My requests',
  'meLeave.none':       'No leave requests yet',
  'meLeave.pending':    'Under review',
  'meLeave.approved':   'Approved ✓',
  'meLeave.rejected':   'Rejected',

  // agent month
  'meMonth.workShifts':    'Work shifts',
  'meMonth.offDays':       'OFF days',
  'meMonth.holidaysWorked':'Holidays worked',
  'meMonth.myComp':        'My compensation days',
  'meMonth.compPending':   '⏳ Comp pending',
  'meMonth.underReview':   'Under review',

  // nav / cards / settings
  'nav.settings':          'Settings',
  'dash.backToCompany':    '← Company',
  'dash.openTeams':        'Open teams',
  'dash.accountSubtitle':  'Teams in this account',
  'dash.emptyAccountTeams':'No teams in this account yet — add one to get started',

  // scheduling mode (team settings)
  'set.schedMode':            'Scheduling mode',
  'set.schedModeHint':        'How this team weekly schedule is produced',
  'schedMode.self_service':   'Employee preferences',
  'schedMode.self_service.d': 'Employees register their own shifts',
  'schedMode.top_down':       'Management-assigned',
  'schedMode.top_down.d':     'Management assigns; employees view only',
  'schedMode.hybrid':         'Hybrid',
  'schedMode.hybrid.d':       'Employees register and managers edit / fill gaps',

  // agent top-down note
  'me.topDownNote':        'Your schedule is set by management. Below is your assigned schedule.',

  // company settings
  'cset.title':            'Company Settings',
  'cset.subtitle':         'Company profile and team members',
  'cset.companyName':      'Company name',
  'cset.members':          'Members & roles',
  'cset.membersHint':      'Add people and assign their roles',
  'cset.owner':            'Owner',
  'cset.admin':            'Company admin',
  'cset.account_manager':  'Account manager',
  'cset.team_manager':     'Team manager',
  'cset.addMember':        'Add member',
  'cset.memberEmail':      'Member email',
  'cset.role':             'Role',
  'cset.scope':            'Scope',
  'cset.noMembers':        'No members added yet',
  'cset.pending':          'pending signup',
  'cset.remove':           'Remove',
  'cset.saved':            '✓ Saved!',
}

const ar: Dict = {
  'nav.company':      'الشركة',
  'nav.teams':        'الفرق',
  'nav.appearance':   'المظهر',
  'nav.language':     'اللغة',
  'nav.signOut':      'تسجيل الخروج',
  'nav.backToTeams':  '← الفرق',
  'theme.light':      'فاتح',
  'theme.dark':       'داكن',

  'dash.subtitle':    'الأكونتات والفرق وجداول الشيفتات',
  'dash.newAccount':  'أكونت جديد',
  'dash.createAccount': 'إنشاء أكونت جديد',
  'dash.accountName': 'اسم الأكونت',
  'dash.coverage':    'نوع التغطية',
  'dash.weekStart':   'بداية الأسبوع',
  'dash.cancel':      'إلغاء',
  'dash.saveAccount': '+ إنشاء الأكونت',
  'dash.saving':      'جاري الحفظ…',
  'dash.loading':     'جاري التحميل…',
  'dash.noAccounts':  'لسه مفيش أكونتات',
  'dash.noAccountsHint': 'ابدأ بإنشاء أول أكونت (وحدة عمل) عشان توزّع عليه فرقك',
  'dash.addTeam':     'أضف فريق',
  'dash.noTeams':     'مفيش فرق في الأكونت ده لسه',
  'dash.teamName':    'اسم الفريق',
  'dash.coAdmins':    'إيميلات أدمن مشاركين',
  'dash.managers':    'إيميلات المانجرز',
  'dash.optional':    '(اختياري)',
  'dash.saveTeam':    '+ إنشاء الفريق',
  'dash.teamsCount':  'فريق',
  'dash.managersCount': 'مدير',
  'coverage.custom':  'مخصّص',
  'coverage.24_7':    'تغطية 24/7',

  'team.management':  'إدارة الفريق',
  'team.subtitle':    'اضبط فريقك وأدر الجداول الأسبوعية',
  'team.shifts':      'الشيفتات',
  'team.shifts.desc': 'أنواع الشيفتات ومواعيدها وألوانها',
  'team.requirements': 'المتطلبات',
  'team.requirements.desc': 'الحد الأدنى والأقصى للموظفين لكل شيفت',
  'team.agents':      'الموظفين',
  'team.agents.desc': 'إضافة الموظفين واعتماد الحسابات',
  'team.schedule':    'الجدول',
  'team.schedule.desc': 'عرض المصفوفة والتحقق والتصدير',
  'team.reports':     'التقارير',
  'team.reports.desc': 'إحصائيات وعبء الشيفتات الشهري',
  'team.leaves':      'الإجازات والأرصدة',
  'team.leaves.desc': 'أرصدة الموظفين وطلبات الإجازة',
  'team.holidays':    'الإجازات الرسمية',
  'team.holidays.desc': 'إجازات رسمية وتتبّع أيام التعويض',
  'team.settings':    'الإعدادات',
  'team.settings.desc': 'الأدمنز والمانجرز وإعدادات الفريق',

  'day.0': 'الأحد', 'day.1': 'الإثنين', 'day.2': 'الثلاثاء', 'day.3': 'الأربعاء',
  'day.4': 'الخميس', 'day.5': 'الجمعة', 'day.6': 'السبت',
  'dayShort.0': 'أحد', 'dayShort.1': 'إثنين', 'dayShort.2': 'ثلاثاء', 'dayShort.3': 'أربعاء',
  'dayShort.4': 'خميس', 'dayShort.5': 'جمعة', 'dayShort.6': 'سبت',

  'common.backToTeam': '← الفريق',
  'common.loading':    'جاري التحميل…',
  'common.add':        'إضافة',
  'common.saved':      '✓ اتحفظ!',

  'auth.tagline':    'سجّل دخولك لإدارة جداول فريقك',
  'auth.google':     'المتابعة بجوجل',
  'auth.orEmail':    'أو بالإيميل',
  'auth.email':      'الإيميل',
  'auth.password':   'كلمة المرور',
  'auth.signingIn':  'جاري الدخول…',
  'auth.signIn':     'تسجيل الدخول',
  'auth.signUp':     'إنشاء حساب',
  'auth.checkEmail': 'راجع إيميلك لتأكيد الحساب.',

  'shifts.title':         'إعداد الشيفتات',
  'shifts.addType':       'إضافة نوع شيفت',
  'shifts.name':          'الاسم',
  'shifts.namePlaceholder':'مثال: صباحي',
  'shifts.start':         'وقت البداية',
  'shifts.end':           'وقت النهاية',
  'shifts.color':         'اللون',
  'shifts.isOff':         'ده شيفت "إجازة / يوم راحة"',
  'shifts.adding':        'جاري الإضافة…',
  'shifts.add':           'إضافة شيفت',
  'shifts.colShift':      'الشيفت',
  'shifts.colHours':      'المواعيد',
  'shifts.colType':       'النوع',
  'shifts.dayOff':        'يوم راحة',
  'shifts.shift':         'شيفت',
  'shifts.none':          'مفيش شيفتات لسه',
  'shifts.confirmDelete': 'تمسح الشيفت ده؟',

  'req.title':    'مصفوفة المتطلبات',
  'req.subtitle': 'الحد الأدنى والأقصى للموظفين لكل شيفت في كل يوم — سيب الأقصى فاضي لو بدون حد',
  'req.saveAll':  'حفظ الكل',
  'req.saving':   'جاري الحفظ…',
  'req.minMax':   'أدنى / أقصى',
  'req.noShifts': 'مفيش شيفتات لسه.',
  'req.addFirst': 'أضف شيفتات الأول',
  'req.minTitle': 'الحد الأدنى',
  'req.maxTitle': 'الحد الأقصى (فاضي = بدون حد)',

  'set.title':         'إعدادات الفريق',
  'set.teamName':      'اسم الفريق',
  'set.coAdmins':      'أدمنز مشاركين',
  'set.coAdminsHint':  'يقدروا يدخلوا ويديروا الفريق بإيميلاتهم',
  'set.noCoAdmins':    'مفيش أدمنز مشاركين لسه',
  'set.managerEmails': 'إيميلات المانجرز',
  'set.managerHint':   'هيستلموا الجدول النهائي على إيميلاتهم',
  'set.noManagers':    'مفيش مانجرز لسه',
  'set.saveChanges':   'حفظ التغييرات',

  'common.cancel': 'إلغاء',

  'agents.title':          'الموظفين',
  'agents.namePlaceholder':'اسم الموظف',
  'agents.emailPlaceholder':'إيميل الشركة (للدخول)',
  'agents.adding':         'جاري الإضافة…',
  'agents.add':            'إضافة',
  'agents.hint':           'الموظف هيسجّل بنفس الإيميل ده على التول، وبعدها توافق على دخوله من الجدول تحت.',
  'agents.colAgent':       'الموظف',
  'agents.colEmail':       'الإيميل',
  'agents.colStatus':      'الحالة',
  'agents.noEmail':        '— مفيش إيميل —',
  'agents.active':         '✓ مفعّل',
  'agents.pending':        '⏳ بانتظار الموافقة',
  'agents.notSignedUp':    'لم يسجّل بعد',
  'agents.noAccount':      'بدون حساب',
  'agents.approve':        '✓ موافقة',
  'agents.revoke':         'إلغاء التفعيل',
  'agents.move':           'نقل',
  'agents.moveTo':         'نقل لتيم آخر',
  'agents.none':           'لا يوجد موظفين بعد',
  'agents.confirmDelete':  'حذف الموظف وكل جداوله نهائياً؟ استخدم زر النقل بدل الحذف لو عايز تنقله.',
  'agents.moveHeading':    'نقل الموظف',
  'agents.moveDescPre':    'نقل',
  'agents.moveDescPost':   'لتيم آخر. تسجيله الجديد هيكون على التيم الجديد. الجداول القديمة تفضل محفوظة على التيم الحالي.',
  'agents.noOtherTeams':   'لا يوجد تيم آخر للنقل إليه. أنشئ تيم جديد أولاً.',
  'agents.chooseTeam':     'اختر التيم الجديد',
  'agents.choose':         '— اختر —',
  'agents.moving':         'جاري النقل…',
  'agents.moveBtn':        'نقل الموظف',

  'leaves.subtitle':      'حدّد رصيد كل موظف وراجع طلبات الإجازة',
  'leaves.pending':       'طلبات بانتظار المراجعة',
  'leaves.noPending':     'مفيش طلبات معلّقة',
  'leaves.days':          'يوم',
  'leaves.approve':       'قبول',
  'leaves.reject':        'رفض',
  'leaves.colEmployee':   'الموظف',
  'leaves.annualBalance': 'رصيد سنوي',
  'leaves.usedRemaining': 'مستخدم / متبقّي',
  'leaves.sickBalance':   'رصيد مرضي',
  'leaves.save':          'حفظ',
  'leaves.noEmployees':   'لا يوجد موظفين',
  'leaveType.annual':     'سنوية',
  'leaveType.sick':       'مرضية',
  'leaveType.unpaid':     'بدون أجر',

  'hol.title':          'الإجازات الرسمية والتعويضات',
  'hol.subtitle':       'تتبّع من اشتغل في الإجازات الرسمية ومن أخذ تعويضه',
  'hol.granted':        'تعويضات ممنوحة',
  'hol.pendingStat':    'في الانتظار',
  'hol.usedStat':       'تعويضات مستخدمة',
  'hol.add':            'إضافة إجازة رسمية',
  'hol.date':           'التاريخ',
  'hol.name':           'اسم الإجازة',
  'hol.namePlaceholder':'مثال: عيد الأضحى',
  'hol.adding':         'جاري الإضافة…',
  'hol.addBtn':         '+ إضافة',
  'hol.none':           'لا توجد إجازات رسمية مضافة بعد',
  'hol.confirmDelete':  'حذف هذه الإجازة؟ سيتم حذف سجلات التعويض المرتبطة بها.',
  'hol.compBadge':      'تعويض',
  'hol.usedBadge':      'استخدم',
  'hol.searching':      'جاري البحث…',
  'hol.noWorkers':      'لا يوجد أجينتس مسجّلين بشيفت في هذا اليوم',
  'hol.workedThisDay':  'اشتغلوا في هذا اليوم',
  'hol.grantAll':       'منح تعويض للكل',
  'hol.grant':          'منح تعويض',
  'hol.usedOn':         'استخدم',
  'hol.undo':           'تراجع',
  'hol.compGranted':    'تعويض ممنوح',
  'hol.markUsed':       '✓ سجّل استخدام',
  'hol.pendingSummary': 'تعويضات لم تُستخدم بعد',
  'hol.recordUse':      'سجّل استخدام',

  'rep.loading':        'جاري تحميل التقرير…',
  'rep.title':          'تقارير الفريق',
  'rep.subtitle':       'إحصائيات شيفتات كل أجينت على مدار الشهر',
  'rep.agents':         'الأجينتس',
  'rep.workShifts':     'شيفتات الشغل',
  'rep.offDays':        'أيام OFF',
  'rep.monthHolidays':  'إجازات الشهر',
  'rep.noAgents':       'لا يوجد أجينتس',
  'rep.colAgent':       'الأجينت',
  'rep.total':          'إجمالي',
  'rep.nights':         'ليالي 🌙',
  'rep.weekends':       'جُمَع/سبوت',
  'rep.holidaysWorked': 'إجازات اشتغلها',
  'rep.comp':           'التعويض',
  'rep.grandTotal':     'الإجمالي',
  'rep.used':           'مستخدم',
  'rep.hint':           '💡 اضغط على أي أجينت لعرض تقويم شهره كامل وتفاصيل أيام التعويض.',
  'rep.compDays':       'أيام التعويض',
  'rep.compUsedOn':     '✓ اتعوّض يوم',
  'rep.compNotUsed':    '⏳ تعويض لم يُستخدم',
  'rep.compNotGranted': 'لم يُمنح',

  'sched.loading':        'جاري تحميل الجدول…',
  'sched.title':          'جدول الشيفتات',
  'sched.ok':             '✓ تمام',
  'sched.less':           '▼ ناقص',
  'sched.more':           '▲ زيادة',
  'sched.fridayTitle':    '⚠️ تحذير — اليوم الجمعة والجدول لم يُأكَّد بعد!',
  'sched.fridayDesc':     'يُنصح بتأكيد الجدول وإرساله للمانجر قبل نهاية اليوم.',
  'sched.confirmNow':     '🔒 أكد الآن',
  'sched.confirming':     'جاري التأكيد…',
  'sched.confirmed':      '🔒 مؤكَّد',
  'sched.open':           '🟡 مفتوح',
  'sched.confirm':        'تأكيد الجدول',
  'sched.openNext':       'فتح الأسبوع القادم',
  'sched.opening':        'جاري الفتح…',
  'sched.exporting':      'جاري التصدير…',
  'sched.exportEmail':    'تصدير وإرسال',
  'sched.editHint':       '💡 تقدر تعيّن أو تغيّر شيفت أي موظف مباشرة من الجدول — اضغط على أي خانة واختار الشيفت (لسد العجز أو لمن لم يسجّل).',
  'sched.noAgents':       'لا يوجد موظفين بعد.',
  'sched.addAgentsFirst': 'أضف موظفين الأول',
  'sched.colAgent':       'الموظف',
  'sched.notRegistered':  '— غير مسجّل —',
  'sched.assignTitle':    'عيّن أو غيّر الشيفت',
  'sched.validation':     'التحقق',
  'sched.submissions':    'التسجيلات',
  'sched.confirmDialog':  'تقفل الجدول ده؟ الموظفين مش هيقدروا يعدّلوا تسجيلاتهم.',
  'sched.confirmedToast': 'تم تأكيد الجدول ✓',
  'sched.emailedToast':   'تم الإرسال للمانجر ✉️',
  'sched.exportedNoEmail':'اتعمل Export بس الإيميل لم يُرسل:',
  'sched.filesCreated':   'تم إنشاء الملفات ✅',
  'sched.exportFailed':   'فشل الـ Export:',
  'sched.nextOpened':     'تم فتح الأسبوع القادم للتسجيل ✅',
  'sched.complianceTitle':'تنبيهات الامتثال والراحة',
  'sched.complianceDescPre':'فحص تلقائي: أيام متتالية كتير · مفيش يوم راحة · راحة قليلة بين الشيفتات (أقل من',
  'sched.complianceDescPost':'ساعات)',
  'sched.noIssues':       '✓ مفيش أي مخالفات في الأسبوع ده — كله سليم',
  'sched.consecutiveDays':'أيام متتالية بدون راحة',
  'sched.noRestDay':      'مفيش يوم راحة طول الأسبوع',
  'sched.shortRest':      'راحة قليلة',
  'sched.hoursShort':     'س',
  'sched.between':        'بين',
  'sched.and':            'و',

  'me.nav.register':    'تسجيل الجدول',
  'me.nav.month':       'جدولي الشهري',
  'me.nav.leave':       'إجازاتي',
  'me.signOut':         'تسجيل الخروج',
  'me.exit':            'خروج',
  'me.pendingTitle':    'في انتظار موافقة الأدمين',
  'me.pendingHi':       'أهلاً',
  'me.pendingBody':     '— حسابك اتسجّل بنجاح. لسه محتاج الأدمين يوافق على دخولك.',
  'me.noAccessTitle':   'مفيش صلاحية دخول',
  'me.noAccessDesc':    'الإيميل ده لسه مش مضاف لأي فريق. تواصل مع الأدمين.',
  'me.noOpenWeek':      'مفيش أسبوع مفتوح للتسجيل دلوقتي.',
  'me.shortageTitle':   'فيه شيفتات فيها عجز — سجّل فيها وتساعد الفريق 🙌',
  'me.teamSchedule':    'جدول الفريق',
  'me.colEmployee':     'الموظف',
  'me.meSuffix':        ' (أنا)',
  'me.coverage':        'تغطية',
  'me.short':           'عجز',
  'me.full':            'مكتمل',
  'me.need':            'محتاج',
  'me.legShort':        'عجز',
  'me.legOk':           'تمام',
  'me.legFull':         'مكتمل',
  'me.legNone':         'لسه مسجّلش',
  'me.registerMine':    '✍️ سجّل جدولي',
  'me.saving':          'جاري الحفظ…',
  'me.saveMine':        'حفظ جدولي',
  'me.savedToast':      'تم حفظ جدولك ✅',
  'me.liveHint':        'الجدول بيتحدّث لحظياً — كل ما حد يسجّل، التغطية تتغيّر. اعمل تحديث للصفحة لأحدث حالة.',

  'meLeave.request':    'طلب إجازة',
  'meLeave.annual':     'إجازة سنوية',
  'meLeave.sick':       'إجازة مرضية',
  'meLeave.remainingOf':'متبقّي من',
  'meLeave.used':       'استخدمت',
  'meLeave.type':       'نوع الإجازة',
  'meLeave.from':       'من',
  'meLeave.to':         'إلى',
  'meLeave.reason':     'السبب (اختياري)',
  'meLeave.sending':    'جاري الإرسال…',
  'meLeave.send':       'إرسال الطلب',
  'meLeave.myRequests': 'طلباتي',
  'meLeave.none':       'مفيش طلبات إجازة بعد',
  'meLeave.pending':    'قيد المراجعة',
  'meLeave.approved':   'مقبولة ✓',
  'meLeave.rejected':   'مرفوضة',

  'meMonth.workShifts':    'شيفتات شغل',
  'meMonth.offDays':       'أيام OFF',
  'meMonth.holidaysWorked':'إجازات اشتغلتها',
  'meMonth.myComp':        'أيام التعويض بتاعتي',
  'meMonth.compPending':   '⏳ تعويض لسه',
  'meMonth.underReview':   'قيد المراجعة',

  'nav.settings':          'الإعدادات',
  'dash.backToCompany':    '← الشركة',
  'dash.openTeams':        'افتح الفرق',
  'dash.accountSubtitle':  'الفرق في الأكونت ده',
  'dash.emptyAccountTeams':'مفيش فرق في الأكونت ده لسه — أضف واحد للبداية',

  'set.schedMode':            'نمط الجدولة',
  'set.schedModeHint':        'إزاي جدول الفريق الأسبوعي بيتعمل',
  'schedMode.self_service':   'تفضيلات الموظف',
  'schedMode.self_service.d': 'الموظف يسجّل شيفتاته بنفسه',
  'schedMode.top_down':       'إدارة مباشرة',
  'schedMode.top_down.d':     'الإدارة توزّع؛ الموظف يشوف بس',
  'schedMode.hybrid':         'مختلط',
  'schedMode.hybrid.d':       'الموظف يسجّل والمدير يعدّل / يسدّ العجز',

  'me.topDownNote':        'جدولك بتحدده الإدارة. تحت ده جدولك المعتمد.',

  'cset.title':            'إعدادات الشركة',
  'cset.subtitle':         'بيانات الشركة وأعضاء الفريق',
  'cset.companyName':      'اسم الشركة',
  'cset.members':          'الأعضاء والأدوار',
  'cset.membersHint':      'أضف أشخاص وحدد أدوارهم',
  'cset.owner':            'المالك',
  'cset.admin':            'أدمن الشركة',
  'cset.account_manager':  'مدير أكونت',
  'cset.team_manager':     'مدير فريق',
  'cset.addMember':        'إضافة عضو',
  'cset.memberEmail':      'إيميل العضو',
  'cset.role':             'الدور',
  'cset.scope':            'النطاق',
  'cset.noMembers':        'مفيش أعضاء مضافين لسه',
  'cset.pending':          'لسه مسجّلش',
  'cset.remove':           'إزالة',
  'cset.saved':            '✓ اتحفظ!',
}

const DICT: Record<Lang, Dict> = { en, ar }
